### ISSUE TITLE
Support for deep FFNNs

### ISSUE THREAD

**Issue by mipstian** [collinhundley/Swift-AI#12]
Hi! I've developed a similar library, except focused on customization instead of performance. The only feature I miss from my implementation is the ability to specify an arbitrary number of hidden layers, and it would be nice to see it in Swift-AI.

The way I implemented it, the designated initializer would take an `[Int]` for the `hidden` parameter, each `Int` being the size of that hidden layer. The rest of the interface stays pretty much the same.

P.s. why are all member accesses qualified with `self.`? This is Swift man :)

**Comment by collinhundley** [comment]
Yes, support for multiple hidden layers / deep learning is currently on the roadmap! A few other features have taken priority currently (matrix library, genetic algorithms and example projects), but it's one of the next pieces I'd like to tackle.

Regarding `self`: It's a matter of personal preference, really. I've given both paradigms a shot and being explicit seems to improve readability, clarity and intention, in my opinion. There are perfectly valid arguments on both sides, though.

**Comment by mipstian** [comment]
Nice! I might try implementing it myself too if I have time, then you'll just have to fix my math :)

`self`: my main argument against it (aside from personal preference) is that Swift forces you to use it in specific cases - to disambiguate shadowed identifiers and to make capture semantics explicit. So every time I see `self.` I automatically check what it's shadowing and/or worry about retain cycles :) In other words, not using `self.` is a guarantee that those problems don't apply, hence it reduces cognitive load imo.

**Comment by KacheFlowe** [comment]
@mipstian I agree with that sentiment in general. Unfortunatly the part of my brain that clings to objective-c hasn't realized that.

**Comment by mipstian** [comment]
Relevant https://github.com/apple/swift-evolution/blob/master/proposals/0009-require-self-for-accessing-instance-members.md
I guess we'll see what the direction is, tomorrow :)

**Comment by collinhundley** [comment]
It will be interesting to see what the decision is. If they accept the proposal, then I guess I get a little self-validation and don't have to change any code. If they reject it, then hopefully they give some more guidance and I'll be the first person to switch sides :)

Closing this issue in favor of the conversation on [Issue 25](https://github.com/collinhundley/Swift-AI/issues/25).
