### ISSUE TITLE
Separate Storage

### ISSUE THREAD

**Issue by Danappelxx** [collinhundley/Swift-AI#16]
I believe there was a discussion about it should be possible to use the framework just by dragging in a single file (currently FFNN.swift). Right now, FFNN conforming to Storage is preventing this from happening. What's the issue with moving [this snippet](https://github.com/collinhundley/Swift-AI/blob/master/Source/FFNN.swift#L362) into Storage.swift?

**Comment by collinhundley** [comment]
That is a good idea - I still hope to maintain independence between modules, although as the library grows it will become more difficult.  Feel free to submit a pull request with this change, so you can get credit for it :)

**Comment by mipstian** [comment]
That would cause anyone that needs `Storage` to import `FFNN.swift` even if they don't need it. Maybe a better solution would be a third file `FFNNStorage.swift`.

**Comment by Danappelxx** [comment]
Will do :)

**Comment by collinhundley** [comment]
@mipstian You're right - I overlooked that. Creating a new file is a possibility, but of course that means each class will need its own 'Class'+Storage.swift file, which eventually might get cluttered.  I'm open to suggestions but I'm not sure if that's really preferable to keeping the dependency as it is.

**Comment by mipstian** [comment]
Personally I don't think the one-file import should be a high priority - especially with an official package manager on the horizon. It's not a big deal to import the whole library, and most third-party library code isn't single-file so most people are used to it. Submodules, CocoaPods, Carthage, etc.

I'd actually take it one step further and split more. In my similar library I had 5-6 files in a group to describe the equivalent of the `FFNN` class: `Network` (just the data and initializers), `NetworkPropagation`, `NetworkTraining`, `ActivationFunctions`, you get the idea. Enabling Whole Module Optimization would take care of preserving performance across the split files.

Maybe that's just me, but having small, focused files helps me understand and evolve the codebase faster.

**Comment by collinhundley** [comment]
With the Swift Package Manager, avoiding dependencies between classes will become less of a priority for the reasons @mipstian mentioned.  That said, we won't go to the extreme either.  While splitting the neural network into multiple files might have worked in your project, in my experience it can quickly become unmaintainable.

I've merged [Pull #17](https://github.com/collinhundley/Swift-AI/pull/17) with the Storage extension in its own file, but we'll consider this an exception.  I agree that it's the best solution for right now.

**Comment by Danappelxx** [comment]
I agree with both sides, and as such don't have anything to say :stuck_out_tongue: Thanks for merging the PR!
