### ISSUE TITLE
Re-think the storage, vDSP calls…

### ISSUE THREAD

**Issue by liscio** [collinhundley/Swift-AI#30]
Someone pointed out this code base to me recently, and it's very cool stuff. While poking around I found things like this:

https://github.com/collinhundley/Swift-AI/blob/master/Source/Vector.swift#L14

While I also use a straight-up swift array to back my own publicly-available vectors at https://github.com/liscio/SMUGMath-Swift, I have recently found that it's not a great idea in practice—`Array`s aren't necessarily guaranteed to be contiguous in memory. Instead I would recommend that you use `ContiguousArray<Float>` for the `flat` definition, and also surround your Accelerate accesses using `withUnsafe{,Mutable}Pointer` as I do in the code here: 

https://github.com/liscio/SMUGMath-Swift/blob/master/SMUGMath/RealVectorOperations.swift

I don't yet have concrete plans to put my new code into the repo above because it is still in progress and tightly coupled with something else I'm working on.

Anyway—really cool repo, and subject matter!

**Comment by joeblau** [comment]
@liscio I was browsing the [Swift docs](http://swiftdoc.org/v2.1/type/ContiguousArray/) last weekend and I found this:

> Efficiency is equivalent to that of Array, unless Element is a class or @objc protocol type, in which case using ContiguousArray may be more efficient.

Is there still benefit in using the `ContiguousArray<Float>` since all of the types are primitive?

**Comment by liscio** [comment]
Efficiency != guarantee of contiguous storage. That said, it appears that contiguous storage is guaranteed for `Array`s as well, *only* when used with value types, as you point out.

Reading [Dave Abrahams' original design document](https://github.com/apple/swift/blob/4023896b395fdef4274857f31332b161f4e75964/docs/Arrays.rst) for `Array` confirms that this is still true. So, don't mind me! :)

For what it's worth, and to satisfy my own gut feeling, they don't take the same code paths. For instance, in an `Array`, `withUnsafeBufferPointer` does the following: https://github.com/apple/swift/blob/2d27beccfcf199489174a30cecbad68db1375381/stdlib/public/core/ArrayBuffer.swift#L402

And `withUnsafeBufferPointer` has the following implementation for a `ContiguousArray`: https://github.com/apple/swift/blob/2d27beccfcf199489174a30cecbad68db1375381/stdlib/public/core/ContiguousArrayBuffer.swift#L263

It's a fairly minor difference, but a difference nonetheless. A `ContiguousArray` will be most like a C array, whereas an `Array` has (admittedly very little) extra machinery that you will never need. I personally feel that asserting that fact is worthwhile in the code if you can.

**Comment by joeblau** [comment]
Yes... No...?

**Comment by collinhundley** [comment]
Perhaps @liscio can explain his recommendation of surrounding Accelerate accesses with `withUnsafe{,Mutable}Pointer` - I'm not quite sure I follow that. Other than the `withUnsafeBufferPointer` difference that he pointed out, `Array` and `ContiguousArray` appear to be identical for value types.

**Comment by joeblau** [comment]
Alrighty; seems to be similar to what I found as well; Thanks for looking into it 👍
