### ISSUE TITLE
AI Project

### ISSUE THREAD

**Issue by Agtsaras** [collinhundley/Swift-AI#33]
Hey Collin. I would like to ask if i can use this library to an app that will do this thing: You take a picture of a fruit with your camera and then the app give you results some of the recipes you can make with this fruit! Can i achieve this with this library? If not what should i use to achieve this result? Thanks in advance.

**Comment by JiriTrecak** [comment]
Hey!

Even though I am not Collin, I will still probably able to help you :)

When you are developing like this, we have to always break it into subproblems. For this very vague description, you would have 2 main areas that you would have to solve:

- Take picture and recognize that there is apple there
- Get apple [or any other fruit] receipts 

Now, the first one is solvable through this library - you would need the backpropagation network where you would feed thousands of pictures of apples and (different fruits) and say this is "apple", this is "pear" - that is your training group. When your network is sufficiently trained, you would then feed it with your taken picture and expect one of the outputs (or none of them) as key characterizing the fruit [apple, pear, ..].

For the second problem, you would have to have a database where you would just send that key and it would return you the variations.

Hope it helps!

**Comment by Agtsaras** [comment]
Thanks a lot Jiri. Indeed that help a lot :D

**Comment by collinhundley** [comment]
@JiriTrecak that's a good explanation. Thanks!
