### ISSUE TITLE
Recurrent Neural Network (RNN)

### ISSUE THREAD

**Issue by joobei** [collinhundley/Swift-AI#34]
I am looking to implement an RNN in swift and I'm wondering if there's already some effort underway to add an RNN to Swift-AI. So that there is no duplication of effort. Is there some RNN effort by somebody?

Thanks in advance.

**Comment by KacheFlowe** [comment]
I'd be willing to help you out in that effort if you'd have me, joobei. Sounds like a cool undertaking.

**Comment by KacheFlowe** [comment]
Looks like an RNN is still open and ripe for development (according to the documentation). Plus it's been more than a week. Wanna try? :+1:

**Comment by joobei** [comment]
I have proposed this to Jorden hill from Birdbrain. He doesn't seem interested and I don't know if we can use his RNN as a base. He has "Copyright ® Jorden Hill" so I'm not sure we can.

https://github.com/jordenhill/Birdbrain

**Comment by KacheFlowe** [comment]
I don't see an MIT license so that probably means we should stay away. Not that it matters since I started on the repo last night,

**Comment by KacheFlowe** [comment]
@joobei Honestly dude we could crack this out ourselves. Would you like to sync up? I'm @BaselNotBasil on twitter.

**Comment by joobei** [comment]
Yeah I'm totally interested. I'm in the mountains until Saturday noon but come Saturday afternoon I could get started on this.

**Comment by KacheFlowe** [comment]
Yo! Joobei hit me up at kacheflo we at g mai l  do t c  om.

**Comment by KacheFlowe** [comment]
Check your email, joobei!

**Comment by loopbum** [comment]
Are you guys going to do this here or seperately?

**Comment by loopbum** [comment]
Here's some pseudo-code from wiki for back-propagation through time method of training RNNs,

Back_Propagation_Through_Time(a, y)   // a[t] is the input at time t. y[t] is the output
    Unfold the network to contain k instances of f
    do until stopping criteria is met:
        x = the zero-magnitude vector;// x is the current context
        for t from 0 to n - 1         // t is time. n is the length of the training sequence
            Set the network inputs to x, a[t], a[t+1], ..., a[t+k-1]
            p = forward-propagate the inputs over the whole unfolded network
            e = y[t+k] - p;           // error = target - prediction
            Back-propagate the error, e, back across the whole unfolded network
            Update all the weights in the network
            Average the weights in each instance of f together, so that each f is identical
            x = f(x);                 // compute the context for the next time-step

**Comment by KacheFlowe** [comment]
@loopbum Hello friend! Thanks for the pseudo-code, actually, we'll be working on it here although how we'll apply the code will differ.

**Comment by collinhundley** [comment]
Closing this issue so we can start a new conversation over at [#11](https://github.com/collinhundley/Swift-AI/issues/50).
