### ISSUE TITLE
Question regarding RNN

### ISSUE THREAD

**Issue by KacheFlowe** [collinhundley/Swift-AI#36]
Hi Colin, 

I'm working on building an RNN right now. Naturally an effective RNN needs a tokenizer. Would you prefer a tokenizer built from scratch or are we allowed to leverage other libraries? In particular, I was thinking of Ayaka Nonaka's Parsimmon's tokenizer feature. Thoughts? 

B

**Comment by collinhundley** [comment]
Hey, it's been a little while.  Let's talk about this over at [#50](https://github.com/collinhundley/Swift-AI/issues/50).
