### ISSUE TITLE
Using Swift AI to detect emotion?

### ISSUE THREAD

**Issue by steve21124** [collinhundley/Swift-AI#38]
http://blogs.microsoft.com/next/2015/11/11/happy-sad-angry-this-microsoft-tool-recognizes-emotions-in-pictures/

how easy is it to use Swift AI to detect emotion?

**Comment by johndpope** [comment]
to solve this problem today - you might want to take a look at the google ai library which you can throw images at and get a response back, along with periphery data. 

I saw a talk at NYC the other week by @genekogan https://github.com/ml4a/ml4a.github.io
he created this javascript masterpeice to detect / recognise objects using convolutional neural nets
https://ml4a.github.io/dev/demos/cifar_confusion.html

I'd love to see someone port this example over to swift.

**Comment by johndpope** [comment]
had a crack on this project / branch here - > https://github.com/johndpope/ios-caffe-ObjectRecognition it will detect stuff based on the trained convolution net. you just need to hot wire it to an emotions.caffemodel

**Comment by steve21124** [comment]
thank you for the detail update. I have try to use openCV before. it is a little bit slow in the past.

**Comment by johndpope** [comment]
https://github.com/danduncan/HappyNet - these scripts should be able to create an emotional neural net for caffe. 
I'm looking at some real time detection using this https://developer.apple.com/library/ios/samplecode/SquareCam/Introduction/Intro.html#//apple_ref/doc/uid/DTS40011190
