### ISSUE TITLE
Interesting Parallels 

### ISSUE THREAD

**Issue by KacheFlowe** [collinhundley/Swift-AI#43]
Hey @collinhundley am I going out on a limb here by saying that the FFD and RNN are similar with the exception of the RNN possessing what appear to be recursive qualities?

**Comment by angu** [comment]
My 2 cents: RNN has a "memory" behavior that the FFD doesn't have.
From wikipedia: 

> Unlike feedforward neural networks, RNNs can use their internal memory to process arbitrary sequences of inputs. This makes them applicable to tasks such as unsegmented connected handwriting recognition[1] or speech recognition.[2]

**Comment by KacheFlowe** [comment]
@angu Yeah there are a great deal of difference, but I thought it a simple way for a user to first conceptualize RNN as similar to FFD ifor conceptual purposes. Of course there are a great deal of benefits;
