### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by telip007** [collinhundley/Swift-AI#44]
Can someone explain me these lines: `let x = (-500 + (Float(index) * 1000) / Float(self.numPoints)) / 100
                    try! self.network.update(inputs: [x])
                    let answer = self.sineFunc(x)
                    print("\(x):\(answer)")
                    try! self.network.backpropagate(answer: [answer])`
I don't get where the AI calculates the points here.

**Comment by telip007** [comment]
And where he gives them out...

**Comment by KacheFlowe** [comment]
....File extension/name?

**Comment by telip007** [comment]
It is in the examples, where the sine curve is calculated
iOS Examples

**Comment by telip007** [comment]
I'm new to machine learning :D

**Comment by telip007** [comment]
Isn't the y calculated in the sinefunc ? And nowhere is the value,which the AI guesses, stored

**Comment by KacheFlowe** [comment]
ok bud you're gonna have to give me a file name

**Comment by telip007** [comment]
Graphviewcontroller.swift

**Comment by angu** [comment]
Please try to not post multiple comments
`for index in 0..<self.numPoints {
                    let x = (-500 + (Float(index) * 1000) / Float(self.numPoints)) / 100
                    try! self.network.update(inputs: [x])
                    let answer = self.sineFunc(x)
                    try! self.network.backpropagate(answer: [answer])
                }`
You are in the training phase.
The network "prediction" is done in the computePoints() function where in fact you can see:
`return (0..<self.numPoints).map { index -> CGFloat in
            let x = (-500 + (Float(index) * 1000) / Float(self.numPoints)) / 100
            let networkY = try! self.network.update(inputs: [x]).first!
            return CGFloat(networkY * -250) + 125
        }
`

Then the point are updated  here 
`    private func updatePoints(ys: [CGFloat]) {
        for index in 0..<self.numPoints {
            self.points[index].transform = CATransform3DMakeTranslation(0, ys[index], 0)
        }
    }`
and then they are showed on the view

**Comment by telip007** [comment]
oh, ok thank you didn't look at the function.
