### ISSUE TITLE
Carthage / Cocoapods support

### ISSUE THREAD

**Issue by va3093** [collinhundley/Swift-AI#49]
Hey guys,

I am thinking about making a PR for you guys to support Cocoapods and carthage. You mentioned in that you don't want to do this because your not sure how they will support other platforms in the future. I aggree. Thats why I think 3rd parties should support Cocoapods, Carthage and Swift package manager. If we supported Cocoapods and Carthage we would need to create a Xcode project and that would help a lot on the testing and CI front. What do you guys think. Would you accept this kind of PR?

**Comment by collinhundley** [comment]
Hey @va3093, thanks for bringing this up. Now that SPM has matured, we'll be using that as our package manager.
