### ISSUE TITLE
Recurrent Neural Network

### ISSUE THREAD

**Issue by collinhundley** [collinhundley/Swift-AI#50]
@KacheFlowe @joobei  Hey guys, sorry for my apparent lack of communication over the last little while.  New startup, crazy hours, no sleep... you know the routine!  Definitely haven't left Swift AI behind though, and in fact it's finally made its way back up my priority list.

It's been some time since we've discussed Recurrent Neural Networks - any progress or thoughts from you guys?  I've decided that it's the next component I want to tackle, partly because it would be particularly useful for some side projects that I have in mind.  I definitely don't want to duplicate any effort that people have already made, if any, so I'd love to hear what you guys think about the idea.

**Comment by KacheFlowe** [comment]
Hey Colin. I've Ben working on this but I've been quiet because of been
applying to jobs. We can tag team if you'd like. I've been working on an
actual demo that makes use of NLP.

**Comment by collinhundley** [comment]
@KacheFlowe Awesome, NLP is exactly what I want to do with it.  I won't be able to put quite the full-time effort into this as I was before, so don't worry about being busy.  We all have normal lives too.

**Comment by KacheFlowe** [comment]
Perfect. Sounds like we're on the same page. Originally I wanted to build
it from the ground up but I may have to make use of NSLinguistic. We'll
see!

**Comment by collinhundley** [comment]
NSLinguisticTagger might be our best option on iOS/OS X.  I would have preferred a custom solution that could be ported to Linux, but the current state of Swift on Linux is shaky at best so I'd be more inclined to just build it for iOS/OS X now and port it later when needed.  Some ideas I have in mind would probably need to be trained on AWS, but I can just make due with a Mac for now.

**Comment by AusCoder** [comment]
Hi guys, sorry if this is not the place for this comment. I am looking around for an open source project to get involved with and this one looks pretty cool. I don't know too much about swift but would love to learn, I do know a bit about machine learning though. Do you guys have any suggestions/recommendations on getting involved?

**Comment by collinhundley** [comment]
@AusCoder Hi, we always appreciate more help. What kind of experience do you have with machine learning? As mentioned in this thread, the next component of Swift AI that I'd like to complete is a recurrent neural network - so if you have any knowledge in that area, it would be particularly useful right now.  But I'm also open to working on other components like a convolutional network, genetic algorithms, adding support for deep learning, GPU acceleration, etc.

To familiarize yourself with this library, I'd recommend reading the docs [here](https://github.com/collinhundley/Swift-AI/blob/master/Documentation/FFNN.md#multi-layer-feed-forward-neural-network) and checking out the [demo app](https://github.com/collinhundley/Swift-AI/tree/master/Examples) for a fun little example of what the feed-forward neural network can do.

For Swift itself, I'd highly recommend reading [The Swift Programming Language](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/).  It's no romance novel, but there's probably no better resource for learning the language.

**Comment by AusCoder** [comment]
@collinhundley In terms of machine learning: I have done the Coursera machine learning course and have implemented a couple of the algorithms from that course. I'd love you help out with the recurrent neural network, if I can somehow. Do you guys plan out who will write certain pieces of code?

Thanks for the recommendations with the docs and the Swift reference. I'll have a look at them.

**Comment by KacheFlowe** [comment]
There doesn't seem tp be a written plan. Seems like we just work on it as
we go. Would you like to plan a meetup with me, Sebastian? I could
certainly use your brains! ka c h e @ g m a i l    .c o m
ᐧ

On Tue, May 3, 2016 at 12:37 PM, Sebastian Mueller <notifications@github.com

**Comment by collinhundley** [comment]
I'd love to be involved with that as well, so I don't end up duplicating anybody's work.  My email is in the main readme if you guys wanna do a group message.

**Comment by KacheFlowe** [comment]
I can dig it.
ᐧ

**Comment by AusCoder** [comment]
I sent you guys an email. @KacheFlowe it wouldn't deliver to your email address, however.

**Comment by KacheFlowe** [comment]
Kacheflowe@gmail.com with a lowercase.

**Comment by johndpope** [comment]
maybe this use case / story telling from images would be interesting to tackle for show casing this ai library.  https://github.com/ryankiros/neural-storyteller

**Comment by joobei** [comment]
Guys I have been busy with some other projects but I'm interested in returning to this. Any progress?

**Comment by Jxrgxn** [comment]
There is--I exist.

**Comment by collinhundley** [comment]
Old conversation. See #60

**Comment by JoeriBultheel** [comment]
Kind of late here, but what I want to accomplish is doing inference BUT especially also training of a RNN on iOS! Seems like what you guys are building is closest to this. All other libraries are only for inference and not training :/ 
 
Any progress? Is it a secret repo? :-p. Would love to contribute/stay in the loop.

Love.

**Comment by Aneapiy** [comment]
Hey @JoeriBultheel, I don't have an RNN version, but I used Swift-AI's version of FNN to do training and classification on iOS (iPhone 6s) for a project called [Swift-HAR](https://github.com/Sapphirine/Swift-HAR). Not sure if it's something you can use, but I figured I'd throw it out there.

**Comment by JoeriBultheel** [comment]
@Aneapiy Thnx!

Actually I found this other project https://github.com/jordenhill/Birdbrain which is closer to what I want to achieve. I love swift-ai's code a lot though, would be nice to see an RNN implementation in the future.
