### ISSUE TITLE
Basic neural network subroutines (BNNS) in Accelerate framework

### ISSUE THREAD

**Issue by neoneye** [collinhundley/Swift-AI#59]
Found this while looking at the whats new in macOS 10.12 Sierra and iOS 10
https://developer.apple.com/library/content/releasenotes/MacOSX/WhatsNewInOSX/Articles/OSXv10.html

I see that the Accelerate framework has gotten support for BNNS 
https://developer.apple.com/reference/accelerate/1912851-bnns

Maybe BNNS yields better performance than vDSP.

**Comment by collinhundley** [comment]
See #60
