### ISSUE TITLE
won't compile under Xcode 8

### ISSUE THREAD

**Issue by indieshack** [collinhundley/Swift-AI#67]
getting multiple errors, e.g.
![screen shot 2016-12-22 at 11 20 22 am](https://cloud.githubusercontent.com/assets/8550631/21437402/7e6f6712-c838-11e6-89c8-8660adce2da1.png)

**Comment by collinhundley** [comment]
Hey @indieshack, this repo isn't compatible with Xcode 8 or Swift 3 yet.  See #60 for more info!
