### ISSUE TITLE
Cannot compile under new Swift 3 (need for latest iOS)

### ISSUE THREAD

**Issue by kwccoin** [collinhundley/Swift-AI#70]
I accept conversion (no choice) but then 2 error messages:
1.

    public func toString(decimalPlaces: Int) -> String {
        let power = pow(10.0, Double(decimalPlaces))
        return "\(round(power * self) / power)"
    }

--> cannot use mutating member on immutable value "self" is immutable ...

and 

2.

let providerRef = CGDataProvider(data: Data(bytes: UnsafePointer<UInt8>(&data), count: data.count * sizeof(PixelData)))

--> ambiguous use of 'init'

**Comment by elvisyzhao** [comment]
Did anyone fix the problem?

**Comment by bearjaw** [comment]
This should solve your problem: http://stackoverflow.com/questions/39579121/swift-3-and-xcode8-ambiguous-use-of-init

**Comment by jonasman** [comment]
can the author merge any of the swift 3 branches?

**Comment by collinhundley** [comment]
Please see version 2.0!
