### ISSUE TITLE
Where is actually the code?

### ISSUE THREAD

**Issue by kokinarido** [collinhundley/Swift-AI#80]
"Swift AI is a high-performance deep learning library " --> but where is the code? Is it this only library https://github.com/Swift-AI/NeuralNet ?

**Comment by collinhundley** [comment]
Hi, the code and examples are linked to in the readme. If you look at the organization account you can see each repository under Swift AI.

**Comment by kokinarido** [comment]
What each? There's only single repository in readme -- NeuralNet, others are examples which don't count.

**Comment by kokinarido** [comment]
What each? There's only single repository in readme -- NeuralNet, others are examples which don't count.

**Comment by mikkelee** [comment]
Go to the organization page as Collin said. It's @Swift-AI

**Comment by kokinarido** [comment]
@mikkelee are you an idiot? I've said -- I've seen that, that's a different repository.
whereas in this repository there're 341 commits and zero code.

**Comment by collinhundley** [comment]
@kokinarido This repository used to contain the main neural net code, before the organization account was created and the components were broken out into their own modules.

Trolls are not welcome here. You appear to be very intelligent, so you'll probably find that your own code suits you better.

**Comment by mikkelee** [comment]
wow, rude.

**Comment by kokinarido** [comment]
>Trolls are not welcome here.

Really? I thought they were.
